version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "patel-todo-app-task"
        LoadBalancerInfo:
          ContainerName: "todo-app"
          ContainerPort: 3000
